[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
eframe = "0.31.1"

egui_extras = { version = "0.31.1", features = ["datepicker"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

env_logger = "0.11.8"